name: branch

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  jsonnet:
    runs-on: ubuntu-latest
    container:
      image: quay.io/coreos/jsonnet-ci:release-0.38
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Make
        run: |
          cd monitoring
          jb install
          make all test
      
      - name: Upload Release Assets
        uses: svenstaro/upload-release-action@v1-release
        if: startsWith(github.ref, 'refs/tags/')
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: out/*
          tag: ${{ github.ref }}
          file_glob: true
